# Generated by Django 5.2.2 on 2025-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
