# Generated by Django 5.2.2 on 2025-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_savedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
