# Generated by Django 5.2.2 on 2025-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_is_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
