# Generated by Django 5.2.4 on 2025-08-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_author_remove_paper_author_paper_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
