# Generated by Django 5.2.4 on 2025-08-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_paper_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.JSONField(default=list),
        ),
    ]
