# Generated by Django 5.2.4 on 2025-08-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_remove_paper_authors_delete_author_paper_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_citation', models.TextField()),
                ('score', models.FloatField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.paper')),
                ('source_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_citations', to='papers.paper')),
            ],
        ),
    ]
