# Generated by Django 5.1.11 on 2025-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_matchedcitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
