# Generated by Django 5.1.11 on 2025-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_alter_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
