# Generated by Django 5.2.4 on 2025-08-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_paper_college_paper_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='local_doi',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
