# Generated by Django 5.2.4 on 2025-08-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_paper_is_registered_paper_local_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='college',
            field=models.CharField(blank=True, choices=[('ccs', 'College of Computer Studies'), ('cba', 'College of Business and Accountancy'), ('cas', 'College of Arts and Sciences'), ('coe', 'College of Engineering'), ('cihm', 'College of International Hospitality Management')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='program',
            field=models.CharField(blank=True, choices=[('bsit', 'BS in Information Technology'), ('bscs', 'BS in Computer Science'), ('bsba', 'BS in Business Administration'), ('bse', 'Bachelor of Secondary Education'), ('bsa', 'Bachelor of Science in Accountancy')], max_length=100, null=True),
        ),
    ]
