# Generated by Django 5.2.4 on 2025-08-19 07:50

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_alter_paper_college_alter_paper_program'),
    ]

    operations = [
        VectorExtension()
    ]
