# Generated by Django 5.2.4 on 2025-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready for Review'), ('complete', 'Complete')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='program',
            field=models.CharField(blank=True, choices=[('bsit', 'BS in Information Technology'), ('bscs', 'BS in Computer Science'), ('bsba', 'BS in Business Administration'), ('bse', 'BS in Secondary Education'), ('bsa', 'BS in Accountancy')], max_length=100, null=True),
        ),
    ]
