# Generated by Django 5.2.4 on 2025-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_paper_status_alter_paper_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
