# Generated by Django 5.2.4 on 2025-09-26 12:22

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0017_paper_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('chunk_id', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'indexes': [models.Index(fields=['paper_id'], name='papers_pape_paper_i_8a077d_idx')],
            },
        ),
    ]
