# Generated by Django 5.2.4 on 2025-09-26 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_paperchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperchunk',
            name='paper_id',
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper'),
        ),
    ]
