# Generated by Django 5.2.4 on 2025-09-28 06:47

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0019_remove_paperchunk_paper_id_paperchunk_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract_embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
