# Generated by Django 5.2.4 on 2025-10-03 11:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0020_paper_abstract_embedding_paper_title_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract_embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='paperchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
