# Generated by Django 5.2.4 on 2025-10-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0022_extractedfigure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation_count_cached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='matched_count_cached',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchedcitation',
            name='matched_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_matched_citations', to='papers.paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='college',
            field=models.CharField(blank=True, choices=[('ccs', 'College of Computer Studies'), ('cba', 'College of Business and Accountancy'), ('cas', 'College of Arts and Sciences'), ('coe', 'College of Engineering'), ('cihm', 'College of International Hospitality Management')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='program',
            field=models.CharField(blank=True, choices=[('bsit', 'BS in Information Technology'), ('bscs', 'BS in Computer Science'), ('bsba', 'BS in Business Administration'), ('bse', 'BS in Secondary Education'), ('bsa', 'BS in Accountancy')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tags',
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='matchedcitation',
            index=models.Index(fields=['source_paper'], name='papers_matc_source__3a531b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchedcitation',
            index=models.Index(fields=['matched_paper'], name='papers_matc_matched_8b9a43_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['college', 'program', 'year'], name='papers_pape_college_026697_idx'),
        ),
    ]
