# Generated by Django 5.2.4 on 2025-10-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0023_paper_citation_count_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
