# Generated by Django 5.2.4 on 2025-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0024_paper_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='images_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='merged_html',
            field=models.FileField(blank=True, null=True, upload_to='papers/merged_html/'),
        ),
    ]
