# Generated by Django 5.2.4 on 2025-10-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0026_create_index_paperchunk_text_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
