# Generated by Django 5.2.4 on 2025-10-31 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0028_alter_tag_options_tag_description_tag_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.RegexValidator(message='Year must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
