# Generated by Django 5.2.4 on 2025-11-01 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_size', models.IntegerField(default=1000, help_text='Size of text chunks for embedding', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)])),
                ('chunk_overlap', models.IntegerField(default=200, help_text='Overlap between consecutive chunks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('appendix_cutoff', models.IntegerField(default=5000, help_text='Character count after which to check for appendices')),
                ('top_k_results', models.IntegerField(default=5, help_text='Number of top results to return', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('min_similarity_score', models.FloatField(default=0.25, help_text='Minimum similarity score threshold', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('bm25_weight', models.FloatField(default=0.5, help_text='Weight for BM25 keyword matching', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vector_weight', models.FloatField(default=0.5, help_text='Weight for vector similarity', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_chunks_scan', models.IntegerField(default=2000, help_text='Maximum chunks to scan in keyword search', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('hybrid_search_multiplier', models.IntegerField(default=2, help_text='Multiplier for initial hybrid search (top_k * multiplier)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hybrid_search_min_results', models.IntegerField(default=20, help_text='Minimum results to fetch for hybrid search')),
            ],
            options={
                'verbose_name_plural': 'Search Settings',
            },
        ),
    ]
