# Generated by Django 5.2.4 on 2025-11-01 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsettings',
            name='tag_cache_timeout',
            field=models.IntegerField(default=3600, help_text='Cache timeout for tags in seconds (default: 1 hour)', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='searchsettings',
            name='tag_extraction_min_score',
            field=models.FloatField(default=0.5, help_text='Minimum similarity score for tag extraction', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='searchsettings',
            name='tag_extraction_top_n',
            field=models.IntegerField(default=5, help_text='Number of top tags to extract', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
