# Generated by Django 5.2.4 on 2025-11-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_llamasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsettings',
            name='settings_cache_timeout',
            field=models.IntegerField(default=900, help_text='How long to cache these settings (seconds). 15 min = 900.'),
        ),
    ]
