# Generated by Django 5.2.4 on 2025-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_searchsettings_settings_cache_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsettings',
            name='embedding_model_name',
            field=models.CharField(default='ibm-granite/granite-embedding-english-r2', help_text='The HuggingFace repo ID or local path for the embedding model.', max_length=255),
        ),
    ]
